### ISSUE TITLE
Este proyecto necesita un nombre...

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/calendario#5]
**Ideas!!** 😃

**Comment by sergormo** [comment]
brain storming: assemblies, times, places, caleve, meetpoints, eventhub, ehub, geekhub, codingdays, codays, moments, ...

**Comment by UlisesGascon** [comment]
Me gusta mucho meetpoints, geekhub, eventhub y codays 👍

**Comment by Josheriff** [comment]
No me gusta escribir para eliminar nombres, pero no se me ocurre ninguno ahora mismo, lo que sí diría es que geekhub , codingdays y codays no los pondría pues la idea es que la herramienta la usen developers y no developers, pueden ser eventos de la calidad de la leche en las vacas alimentadas con pasto...

**Comment by IgnaciodeNuevo** [comment]
Meetingpoint o Eventhub +1

**Comment by Josheriff** [comment]
que tal una mezcla de ambos... Meethub o EventPoint, o.... EventDate

EventDate parece muy obvio y por eso me gusta

**Comment by UlisesGascon** [comment]
MeetHub.... mola! Recordad que no necesitamos un dominio disponible... ya que seguramente el proyecto sea subido como subdominio de osweekends.com

**Comment by IgnaciodeNuevo** [comment]
EventHub o MeetHub molan ambos

**Comment by sergormo** [comment]
Entre Meethub y EventHub sugiero mas EventHub, por distanciarse un poco de Meetup.
El de EventPoint, me gusta, lo pondría en plural, EventPoints, ademas con los Points se pueden hacer juegos chulos en front. 

Del estilo asociar un Point por evento y jugar con colores por tipo de evento, asociar un mapa con puntos mas grandes o no en función del numero de personas, etc puede ser un juego para estructurar el front, branding, eventos, asistencia, D3.js, y se me va ya la cabeza... 
- Cuantos points tengo este mes? hmmm... ;)

**Comment by UlisesGascon** [comment]
Pues... eventPoints es como se llamará :)
